
export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT: 'LOGOUT',
    HIDE_TAB: 'HIDE_TAB',
    SHOW_TAB: 'SHOW_TAB',
    KEYBOARD_SHOWN: 'KEYBOARD_SHOWN',
    KEYBOARD_HIDDEN: 'KEYBOARD_HIDDEN',
    UPDATE_NEW_ORDER_COUNT: 'UPDATE_NEW_ORDER_COUNT',
    RETRIEVED_REMAINING_ORDERS: 'RETRIEVED_REMAINING_ORDERS',
    UPDATE_REMAINING_ORDERS_STATUS: 'UPDATE_REMAINING_ORDERS_STATUS'
};